on:
  workflow_dispatch:
    inputs:
      vartest:
        description: 'testing variable'
        required: false
        default: 'Hello World'
        type: string
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "${{ inputs.vartest }}!" > new_file.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "test"
          git push
