on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v3

      - name: Create new file
        run: |
          echo "Hello, world!" > new_file.txt
