on:
  workflow_dispatch:
    inputs:
      cellnb:
        description: 'cell number'
        required: true
        default: '-9'
        type: string
jobs:
  example-job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - run: |
          if [[ ${{inputs.cellnb}} -lt 0 ]]; then
            bash scripts/select.sh ${{inputs.cellnb}}
          else
            bash scripts/draw.sh ${{inputs.cellnb}}
          fi
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "test"
          git push
